### ISSUE TITLE
[Tool Bug] 

### ISSUE THREAD

**Issue by LTZDLY** [brsf11/mugen-riscv#4]
### 请选择：

- [X] 我已经检查了 [Issue](https://github.com/brsf11/mugen-riscv/issues)，进行了搜索，但没有发现类似问题
- [x] 这个问题可以在多个测试用例上复现
- [ ] 我正在着手修复该问题
- [ ] 我希望接手该问题

### 应该发生什么?

运行该测试例后，测试通过了，在logs和result目录下看见了新生成的文件

### 实际上发生了什么?

运行该测试例后，新文件确实生成了，但是他将原来文件里原有的所有东西全给删掉了
![image](https://user-images.githubusercontent.com/57028291/185363810-3c146515-eeb1-4198-a2d0-e60a64e2b3f3.png)

### 该问题发生的环境

不确定

**Comment by brsf11** [comment]
测试运行前会清除logs和results目录下的文件  
这是为了保证最后整理结果时拷贝的出错用例的日志文件是最新的，所以其实是一个偷懒的做法  
可以加入一个日志文件的匹配功能替代来解决这个问题
